//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNotifyWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOKEN
    {
        public int ID { get; set; }
        public Nullable<int> QRId { get; set; }
        public string TokenInf { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
